//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBooks.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public class voucher_pro
    {
        DB_MYBOOKSEntities database = new DB_MYBOOKSEntities();
       
        public int ID { get; set; }
        public string IDVoucher { get; set; }
        public string IDBook { get; set; }
        public string Script { get; set; }
        //public string MoTa { get; set; }
        public virtual Book Book { get; set; }
        public virtual VOUCHER VOUCHER { get; set; }




    }
}
