//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBooks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int ID { get; set; }
        public string IDProduct { get; set; }
        public Nullable<int> IDOrder { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> PriceOld { get; set; }
        public Nullable<double> PriceNew { get; set; }
        public string IDVoucher { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual OrderPro OrderPro { get; set; }
        public virtual VOUCHER VOUCHER { get; set; }
    }
}
