//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBooks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VOUCHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VOUCHER()
        {
            this.CartLists = new HashSet<CartList>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.voucher_pro = new HashSet<voucher_pro>();
        }
        [StringLength(10, ErrorMessage ="Số kí tự tối đa là 10")]
        [Required]
        public string MAVOUCHER { get; set; }
        [Required]
        [Range(0.0000001, 1.00, ErrorMessage = "Phải lớn hơn 0 và là số")]
        public Nullable<decimal> GIAM { get; set; }
        [Required]
        public string MoTa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartList> CartLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<voucher_pro> voucher_pro { get; set; }
    }
}
